name: Angular CI
on:
  workflow_dispatch
  
  #push:
    #branches:
      #- master
      #- dev
  #pull_request:
    #branches:
      #- master
      #- dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use the secret
        run: echo ${{ secrets.USERNAME }}
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ng build --configuration production

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: anilsb06/angular-image:latest


