name: Angular CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use the secret
        run: echo ${{ secrets.USERNAME }}
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ng build --configuration production

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
      - name: Build docker image 
        run: |
           docker login -u ${{ secrets.API_KEY }} -p ${{ secrets.PASSWORD }}
           docker build -t anilsb06/angular-image .
           docker push anilsb06/angular
        

